name: Globalization Ext. CI/CD Pipeline
on:
  pull_request:
    paths-ignore:
      - .codecov
      - .docfx
      - .github
      - .nuget
      - '**.md'
  workflow_dispatch:
    inputs:
      configuration:
        type: choice
        description: The build configuration to use in the deploy stage.
        required: true
        default: Release
        options:
          - Debug
          - Release

jobs:
  build:
    name: call-build
    strategy:
      matrix:
        configuration: [Debug, Release]
    uses: codebeltnet/jobs-dotnet-build/.github/workflows/default.yml@v2
    with:
      projects: src/**/*.csproj
      configuration: ${{ matrix.configuration }}
      strong-name-key-filename: globalization.snk
    secrets: inherit

  pack:
    name: call-pack
    needs: [build]
    strategy:
      matrix:
        configuration: [Debug, Release]
    uses: codebeltnet/jobs-dotnet-pack/.github/workflows/default.yml@v2
    with:
      configuration: ${{ matrix.configuration }}
      version: ${{ needs.build.outputs.version }}

  test:
    name: call-test
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022]
        configuration: [Debug, Release]
    uses: codebeltnet/jobs-dotnet-test/.github/workflows/default.yml@v2
    with:
      projects: test/**/*.csproj
      configuration: ${{ matrix.configuration }}
      runs-on: ${{ matrix.os }}
      build-switches: -p:SkipSignAssembly=true
      restore: true

  sonarcloud:
    name: call-sonarcloud
    needs: [build,test]
    uses: codebeltnet/jobs-sonarcloud/.github/workflows/default.yml@v1
    with:
      organization: geekle
      projectKey: globalization
      version: ${{ needs.build.outputs.version }}
    secrets: inherit

  codecov:
    name: call-codecov
    needs: [build,test]
    uses: codebeltnet/jobs-codecov/.github/workflows/default.yml@v1
    with:
      repository: codebeltnet/globalization
    secrets: inherit

  codeql:
    name: call-codeql
    needs: [build,test]
    uses: codebeltnet/jobs-codeql/.github/workflows/default.yml@v1

  deploy:
    if: github.event_name != 'pull_request'
    name: call-nuget
    needs: [build, pack, test, sonarcloud, codecov, codeql]
    uses: codebeltnet/jobs-nuget-push/.github/workflows/default.yml@v1
    with:
      version: ${{ needs.build.outputs.version }}
      environment: Production
      configuration: ${{ inputs.configuration == '' && 'Release' || inputs.configuration }}
    permissions:
      contents: write
      packages: write
    secrets: inherit
